In [2]:
import torch
import numpy as np
from gym.spaces import Box

# Dummy model
input1 = torch.rand((1,2))
input2 = torch.rand((1,2))



full_input = torch.cat((input1, input2), axis=0)

# Operations
# Define some weights for model1 and model2
weight1 = torch.rand((1,2), requires_grad=True)
weight2 = torch.rand((1,2), requires_grad=True)

# Concatenate the weights in order to simultaneously perform weight updates
weights = torch.cat((weight1, weight2), axis=0)

# Keep track of the initial weight values.
old_weights = weights.clone().detach()

# Add a bias to the model.
bias = torch.rand((2,2), requires_grad=True)

# Compute some operation with input, weights and bias
output = torch.abs(torch.mul(full_input, weights) + bias)

# Compute the gradient.

# Define model1 with parameters "weight1" and model2 with parameters "weight2".
optimizers = [torch.optim.Adam(params=[weight1], lr=0.5), torch.optim.Adam(params=[weight2], lr=0.5)]
optimizers[0].zero_grad()
optimizers[1].zero_grad()

output.backward(torch.ones_like(output))
# Update the model weights
optimizers[0].step()
optimizers[1].step()

# Analyze the weight update.
weights = torch.cat((weight1, weight2), axis=0)
print("Weight updates: ", weights - old_weights)

print(bias.grad)
print(weight1.grad)
print(weight2.grad)

Weight updates:  tensor([[-0.5000, -0.5000],
        [-0.5000, -0.5000]], grad_fn=<SubBackward0>)
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0022, 0.3713]])
tensor([[0.7138, 0.0604]])


In [3]:
import torch.nn.functional as F
tt = torch.rand((2,3))
kk = torch.rand((2,5))
needed_padding = torch.nn.functional.relu(torch.tensor(tt.shape) - torch.tensor(kk.shape), inplace=True)
print(needed_padding)
res = F.pad(input=tt, pad=(0,needed_padding[-1],0,0), mode='constant', value=0)
print(res.shape)
print(res)

tensor([0, 0])
torch.Size([2, 3])
tensor([[0.1446, 0.1444, 0.0192],
        [0.5612, 0.2353, 0.1335]])


In [72]:
a = np.array([1,2,3,4,5])
b = torch.Tensor([1,2,3,5,4,2,]).unsqueeze(0).transpose(0,1)

vals = torch.rand((6, 5))
print(vals)

idx = torch.stack([torch.tensor(a) == act for act in b])
print(idx)
print(vals[idx])

AssertionError: Torch not compiled with CUDA enabled

In [5]:
agent_dict = {
'sellers': {
1: {
'type': 'DQNAgent',
'reservation': 12,
'lr': 0.002,
'multiplicity': 2
},
2: {
'type': 'DQNAgent',
'reservation': 14,
'lr': 0.002
}
},
'buyers': {
1: {
'type': 'DQNAgent',
'reservation': 12,
'lr': 0.002,
'multiplicity': 3
},
2: {
'type': 'DQNAgent',
'reservation': 14,
'lr': 0.002
}
}
}
n_agent = {'sellers': 0, 'buyers': 0}
for role in ['sellers', 'buyers']:
    for key in agent_dict[role]:
        n_agent[role] += agent_dict[role][key].get('multiplicity', 1)

a = []
for i in range(3):
    a += i*[i*2 + 1]

In [312]:
a = torch.arange(0,5)
a[2].unsqueeze(0)







tensor([2])